import requests
import time

if __name__ == "__main__":

    BASE_URL_T0 = 'http://localhost:5000'
    BASE_URL_T3 = 'http://localhost:5003'

    # start TTS
    print("Starting TTS...")
    response_T3 = requests.post(f'{BASE_URL_T3}/start')
    print(response_T3.json())

    # while TTS status is running, wait
    print("Waiting for TTS to finish...")
    response_T3 = requests.get(f'{BASE_URL_T3}/status')
    while response_T3.json()["status"] == True:
        response_T3 = requests.get(f'{BASE_URL_T3}/status')
    
    # Read the Audio file generated by TTS
    print("Reading the audio file generated by TTS...")
    response_T0 = requests.post(f'{BASE_URL_T0}/start')
    print(response_T0.json())

    # while ReadAudio status is running, wait
    print("Waiting for ReadAudio to finish...")
    response_T0 = requests.get(f'{BASE_URL_T0}/status')
    while response_T0.json()["status"] == True:
        response_T0 = requests.get(f'{BASE_URL_T0}/status')


    print("Exiting...")
