T0_ReadAudio:
  input_wav_file: data/live/audio_generated.wav
  port: 5000
  python_env_name: nao_env
  python_version: '2.7'
T11_Gesture:
  port: 5011
  python_env: nao_env
  python_version: '2.7'
T1_PersonRecognition:
  input_audio_file: data/live/audio_recorded.wav
  input_model_dir: data/pretrained_models/
  input_people_folder: data/stored/people/
  output_text_file: data/live/person_recognized.txt
  port: 5001
  python_env: T1_env
  python_version: '3.11'
  rejection_threshold: 0.17
T2_TextGeneration:
  input_text_file: data/live/text_prompt.txt
  model_name: openchat
  ollama_generate_options:
    repeat_last_n: 100
    repeat_penalty: 1.9
    temperature: 0.8
    top_k: 50
    top_p: 0.95
  output_text_file: data/live/text_generated.txt
  port: 5002
  python_env: T2_env
  python_version: '3.11'
T3_TTS:
  input_text_file: data/live/text_to_say.txt
  language: fr-fr
  model_name: tts_models/multilingual/multi-dataset/your_tts
  output_wav_file: data/live/audio_generated.wav
  port: 5003
  python_env: T3_env
  python_version: '3.10'
  speaker_wav_file: data/stored/assistant/voices/thomas_oxisoglou.mp3
T4_ActionSelection:
  action_selection_dataset_path: data/stored/assistant/action_selection_training/action_dataset.csv
  input_text_file: data/live/text_to_say.txt
  output_text_file: data/live/action_selected.txt
  port: 5004
  pretrained_model_folder: data/pretrained_models/action_classifier/
  python_env: T4_env
  python_version: '3.11'
T6_RecordAudio:
  channel: 2
  loudness_threshold: 0.6
  output_speech_detected_file: data/live/time_speech_detected.txt
  output_wav_file: data/live/audio_recorded.wav
  port: 5006
  python_env: nao_env
  python_version: '2.7'
  sample_rate: 48000
  seconds_to_keep: 10
T8_STT:
  input_wav_file: data/live/audio_recorded.wav
  model_size: medium
  output_text_file: data/live/text_transcribed.txt
  port: 5008
  python_env: T8_env
  python_version: '3.11'
T9_LEDS:
  input_text_file: data/live/led_rgb.txt
  port: 5009
  python_env: nao_env
  python_version: '2.7'
nao_ip: 192.168.137.64
