T10_RetrieveAndAugment:
  chunk_size: 3000
  input_additional_files: []
  input_database_folder: data/stored/documents/
  input_text_file: data/live/text_transcribed.txt
  load_directory: data/pretrained_models/vectordb/
  number_of_results: 3
  output_csv_file: data/live/documents_context.csv
  output_text_file: data/live/documents_context.txt
  port: 5010
  python_version: '3.11'
T2_TextGeneration:
  input_text_file: data/live/text_prompt.txt
  model_name: vigogne
  ollama_generate_options:
    repeat_last_n: 100
    repeat_penalty: 1.9
    temperature: 0.8
    top_k: 50
    top_p: 0.95
  output_text_file: data/live/text_generated.txt
  port: 5002
  python_version: '3.11'
