#---------------------------------------#
#        FINITE TOOLS PARAMETERS        #
#---------------------------------------#

# Tool 0: Read Audio (from file to NAO)
T0_ReadAudio: {
  python_version: 2.7,
  port: 5000,
  nao_ip: "192.168.0.105",
  input_wav_file: data/live/audio_generated.wav,
}

# Tool 1: Person Recognition
T1_PersonRecognition: {
  python_version: 3.11,
  port: 5001,
  output_text_file: data/live/person_recognized.txt,
}

# Tool 2: Text Generation
T2_TextGeneration: {
  python_version: 3.11,
  port: 5002,
  input_text_file: data/live/text_prompt.txt,
  output_text_file: data/live/text_generated.txt,
  model_name: "mistral", # openchat, mistral, llama2, gemma
  ollama_generate_options: {
    "top_k": 50,
    "top_p": 0.95,
    "temperature": 0.85,
    "repeat_penalty": 1.9,
    "repeat_last_n": 100,
  }
}

# Tool 3: Text to Speech
T3_TTS: {
  python_version: 3.10,
  port: 5003,
  model_name: "tts_models/multilingual/multi-dataset/your_tts", # "tts_models/multilingual/multi-dataset/your_tts", "tts_models/fr/css10/vits"
  language: "fr-fr",
  input_text_file: data/live/text_to_say.txt,
  output_wav_file: data/live/audio_generated.wav,
  speaker_wav_file: data/stored/assistant/voices/teddy_riner.mp3, # eliot_christon, example_reference, jean_pierre_pernaut, perrine_laffont, ptisham, roberto_caurand, teddy_riner
}

# Tool 4: Action Selection
T4_ActionSelection: {
  python_version: 3.11,
  port: 5004,
  input_text_file: data/live/text_to_say.txt,
}

# Tool 5: Perform Action
T5_PerformAction: {
  port: 5005,
}

#---------------------------------------#
#       INFINITE TOOLS PARAMETERS       #
#---------------------------------------#

# Tool 6: Record Audio (from NAO)
T6_RecordAudio: {
  python_version: 2.7,
  port: 5006,
  nao_ip: "192.168.0.105",
  channel: 2,
  output_wav_file: data/live/audio_recorded.wav,
  output_speech_detected_file: data/live/time_speech_detected.txt,
  seconds_to_keep: 10,
  sample_rate: 48000,
  loudness_threshold: 0.5,
}

# Tool 7: Capture Images (from NAO)
T7_CaptureImages: {
  python_version: 2.7,
  port: 5007,
  nao_ip: "192.168.0.105",
  output_image_folder: data/live/images/,
  number_of_images: 10,
  interval: 1,
  video_device_args: {resolution: 2, color_space: 11, fps: 30},
  face_detection_time_ms: 500,
  image_args: {width: 248, height: 248},
}

# Tool 8: Speech to Text
T8_STT: {
  python_version: 3.11,
  port: 5008,
  model_size: medium,
  input_wav_file: data/live/audio_recorded.wav,
  output_text_file: data/live/text_transcribed.txt,
}
