import time

def send_command(command, fast_com_dir):
    with open(fast_com_dir + "command.txt", 'w') as file:
        file.write(command)
        
def get_status(fast_com_dir):
    with open(fast_com_dir + "status.txt", 'r') as file:
        return file.read()


if __name__ == "__main__":

    FAST_COM_T0 = "Tools/T0_ReadAudio/fast_com/"
    FAST_COM_T3 = "Tools/T3_TTS/fast_com/"

    # start TTS
    print("Starting TTS...")
    send_command('start', FAST_COM_T3)
    time.sleep(0.2)

    # while TTS status is running, wait
    print("Waiting for TTS to finish...")
    status_T3 = get_status(FAST_COM_T3)
    while status_T3 != "False":
        print("TTS status is " + status_T3 + ". Waiting...")
        status_T3 = get_status(FAST_COM_T3)
        time.sleep(0.2)
    
    # Read the Audio file generated by TTS
    print("Reading the audio file generated by TTS...")
    send_command('start', FAST_COM_T0)

    # while ReadAudio status is running, wait
    print("Waiting for ReadAudio to finish...")
    status_T0 = get_status(FAST_COM_T0)
    while status_T0 != "False":
        print("ReadAudio status is " + status_T0 + ". Waiting...")
        status_T0 = get_status(FAST_COM_T0)
        time.sleep(0.2)
    
    print("All servers have finished their tasks.")
    print("The audio file generated by TTS has been read.")
    print("The text generated by STT is in text_generated.txt.")
    print("The audio file generated by TTS is in data/live/audio_generated.wav.")

    print("Exiting...")
