import requests
import time

if __name__ == "__main__":

    BASE_URL_T0 = 'http://localhost:5000'
    BASE_URL_T3 = 'http://localhost:5003'
    BASE_URL_T6 = 'http://localhost:5006'
    BASE_URL_T8 = 'http://localhost:5008'

    # start recording and STT at the same time
    print("Recording and STT...")
    response_T6 = requests.post(f'{BASE_URL_T6}/start')
    response_T8 = requests.post(f'{BASE_URL_T8}/start')

    print(response_T6.json())
    print(response_T8.json())

    # Wait for a while to simulate some recording and STT time
    print("Waiting 5 seconds...")
    time.sleep(5)

    # stop recording and STT at the same time
    print("Stopping recording and STT...")
    response_T6 = requests.post(f'{BASE_URL_T6}/stop')
    response_T8 = requests.post(f'{BASE_URL_T8}/stop')

    print(response_T6.json())
    print(response_T8.json())

    # while STT status is running, wait
    print("Waiting for STT to finish...")
    response_T8 = requests.get(f'{BASE_URL_T8}/status')
    while response_T8.json()["status"] == True:
        response_T8 = requests.get(f'{BASE_URL_T8}/status')

    # write the STT result from text_transcribed.txt to text_generated.txt
    print("Writing the STT result to text_generated.txt...")
    with open("data/live/text_transcribed.txt", "r", encoding="utf-8") as file:
        text = file.read()
    with open("data/live/text_generated.txt", "w", encoding="utf-8") as file:
        file.write(text)
    
    # start TTS
    print("Starting TTS...")
    response_T3 = requests.post(f'{BASE_URL_T3}/start')
    print(response_T3.json())

    # while TTS status is running, wait
    print("Waiting for TTS to finish...")
    response_T3 = requests.get(f'{BASE_URL_T3}/status')
    while response_T3.json()["status"] == True:
        response_T3 = requests.get(f'{BASE_URL_T3}/status')
    
    # Read the Audio file generated by TTS
    print("Reading the audio file generated by TTS...")
    response_T0 = requests.post(f'{BASE_URL_T0}/start')
    print(response_T0.json())

    # while ReadAudio status is running, wait
    print("Waiting for ReadAudio to finish...")
    response_T0 = requests.get(f'{BASE_URL_T0}/status')
    while response_T0.json()["status"] == True:
        response_T0 = requests.get(f'{BASE_URL_T0}/status')
    
    print("All servers have finished their tasks.")
    print("The audio file generated by TTS has been read.")
    print("The text generated by STT is in text_generated.txt.")
    print("The audio file generated by TTS is in data/live/audio_generated.wav.")

    print("Exiting...")
